### PR TITLE
Add Build videos, Kata Notebooks and Quantum blog

### PR DESCRIPTION
**Pull request by tcNickolas**

### CODE REVIEW

**Comment by tcNickolas** [comment]
@ebraminio Do you have an idea what is wrong with this change? The lint error says "Awesome list must reside in a valid git repository" - but this is definitely a valid git repo?

**Comment by ebraminio** [comment]
I don't know to be honest, this awesome-lint, a somehow requironment for awesome pages link addition, has added some complexity but has some other upsides so I am merging this and will try to fix it later. Thank you so much!

Also like other awesome pages, can you see if some graphical banner can be designed and added here? I asked a friend of mine but no response after awhile so maybe you have better people around. Thank you again

**Comment by tcNickolas** [comment]
You could ask at https://gitter.im/qsharp-community/community? This is a newly created Q# community chat, it has very few people so it might not have a designer yet, but it will get one eventually - worth a try.

**Comment by ebraminio** [comment]
Oh great idea, should put link of that also, thanks

**Comment by crazy4pi314** [comment]
It is part of the Github org @qsharp-community, which has a page (in progress) here: [qsharp.community](https://qsharp.community/). The idea of the org is to collect community developed projects, libraries, demos, etc. that then the Q# community can help maintain! We are still in the process of finding maintainers and projects that are appropriate to include in the group 💖

**Comment by ebraminio** [comment]
Oh feel free to put a link of that in this listing :) /me going to see whether can the lint complains

**Pull request merged**
